services:
  
  v2raycrm:
    build: .
    image: v2raycrm
    container_name: v2raycrm
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/html/storage
    networks:
      - app-network
    ports:
      - 8000:80


  mysql:
    image: mysql
    restart: always
    hostname: "mysql"
    container_name: mysql
    ports:
      - "8106:3306"
    environment:
      - TZ=Asia/Tehran
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    #      MYSQL_ROOT_HOST: "%"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - app-network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - mysql:db
    ports:
      - 8085:80
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tehran
    networks:
      - app-network

networks:
  app-network:
    driver: bridge