version: '3'

services:

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    image: mariadb
    restart: always
    hostname: "mariadb"
    container_name: mariadb
    ports:
      - "8106:3306"
    environment:
      - TZ=Asia/Tehran
      - MYSQL_ROOT_PASSWORD=u3%^euYEYEYheaelmGP6W3ge2
      - MYSQL_DATABASE=first
      - MYSQL_USER=myUser
      - MYSQL_PASSWORD=u3%^euYEYEYheaelmGP6W3ge2
#      MYSQL_ROOT_HOST: "%"
    volumes:
      - db_data_mariadb:/var/lib/mysql
    networks:
      - safaremoon
#  db:
#    image: dockerhub.ir/mysql:5.7
#    container_name: db
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    volumes:
#      - db_data:/var/lib/mysql
##      - ./init:/docker-entrypoint-initdb.d
#    environment:
#      MYSQL_DATABASE: samsam_db
#      MYSQL_ROOT_PASSWORD: r00tS3cr3tP@ssw0rd
#      MYSQL_PASSWORD: s@ms@mS3cr3tP@ssw0rd
#      MYSQL_USER: samsam
#    networks:
#      - safaremoon

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - mariadb:db
    ports:
      - 8080:80
    environment:
      - MYSQL_USER=userdev
      - MYSQL_PASSWORD=u3%^euYEYEYheaelmGP6W3ge2
      - MYSQL_ROOT_PASSWORD=u3%^euYEYEYheaelmGP6W3ge2
      - TZ=Asia/Tehran
    networks:
      - safaremoon

networks:
  safaremoon:
    driver: bridge

volumes:
  db_data_mariadb:
